["google slides"]
serviceSearch = "gslides"
baseUrl = "https://docs.google.com/presentation/"
names = ["slides"]

["google docs"]
serviceSearch = "gd"
baseUrl = "https://docs.google.com/document/"

["google scholar"]
serviceSearch = "googlescholar"
baseUrl = "https://scholar.google.com/"

["google calendar"]
serviceSearch = "gcal"
baseUrl = "https://calendar.google.com/"
names = ["calendar"]

["google drive"]
serviceSearch = "drive"
baseUrl = "https://drive.google.com/"

["google sheets"]
serviceSearch = "gsheets"
baseUrl = "https://docs.google.com/spreadsheets/"
names = ["sheets", "spreadsheets"]

[goodreads]
serviceSearch = "goodreads"
baseUrl = "https://www.goodreads.com/"

[mdn]
serviceSearch = "mdn"
baseUrl = "https://developer.mozilla.org/en-US/"

[coursera]
serviceSearch = "coursera"
baseUrl = "https://www.coursera.org/"

[gmail]
serviceSearch = "gmail"
baseUrl = "https://mail.google.com/"
names = ["mail", "email", "google mail"]

[amazon]
serviceSearch = "az"
baseUrl = "https://www.amazon.com/"

[wikipedia]
serviceSearch = "wikipedia"
baseUrl = "https://en.wikipedia.org/"
names = ["wiki"]

[yelp]
serviceSearch = "yelp"
baseUrl = "https://www.yelp.com/"

[twitter]
serviceSearch = "twitter"
baseUrl = "https://wwww.twitter.com/"

[reddit]
serviceSearch = "reddit"
baseUrl = "https://www.reddit.com/"

["amazon music"]
serviceSearch = "amusic"
baseUrl = "https://music.amazon.com"

["google music"]
serviceSearch = "gmusic"
baseUrl = "https://play.google.com/music/"

["google play music"]
serviceSearch = "gmusic"
baseUrl = "https://play.google.com/music/"
names = ["google music"]

[pandora]
serviceSearch = "pandora"
baseUrl = "https://www.pandora.com/"

[soundcloud]
serviceSearch = "soundcloud"
baseUrl = "https://soundcloud.com/"
names = ["sound cloud"]

[tunein]
serviceSearch = "tunein"
baseUrl = "https://tunein.com/"
names = ["tune in", "tunein radio", "tune in radio"]

[vimeo]
serviceSearch = "vimeo"
baseUrl = "https://vimeo.com/"

[netflix]
serviceSearch = "netflix"
baseUrl = "https://www.netflix.com/"

["apple maps"]
serviceSearch = "amaps"
baseUrl = "https://maps.apple.com/"

["google maps"]
serviceSearch = "gmap"
baseUrl = "https://maps.google.com/"
names = ["maps"]

["open street maps"]
serviceSearch = "omap"
baseUrl = "https://www.openstreetmap.org/"
names = ["open maps", "openstreetmap"]

[stubhub]
serviceSearch = "stubhub"
baseUrl = "https://www.stubhub.com/"
names = ["stub hub"]

[ticketmaster]
serviceSearch = "ticketmaster"
baseUrl = "https://wwww.ticketmaster.com/"
names = ["ticket master"]

["google translate"]
serviceSearch = "translate"
baseUrl = "https://translate.google.com/"
names = ["translate"]

[instagram]
serviceSearch = "instagram"
baseUrl = "https://www.instagram.com/"
names = ["insta"]

[linkedin]
serviceSearch = "linkedin"
baseUrl = "https://www.linkedin.com/"

[quora]
serviceSearch = "quora"
baseurl = "https://www.quora.com/"

[pinterest]
serviceSearch = "pin"
baseUrl = "https://www.pinterest.com/"
names = ["pin"]

[facebook]
serviceSearch = "facebook"
baseUrl = "https://www.facebook.com/"

[stackexchange]
serviceSearch = "stackexchange"
baseUrl = "https://stackexchange.com/"
names = ["stack exchange"]

[dropbox]
serviceSearch = "dropbox"
baseUrl = "https://www.dropbox.com/"

[dictionary]
serviceSearch = "dcom"
baseUrl = "https://www.dictionary.com/"
names = ["dictionary.com"]

[thesaurus]
serviceSearch = "thesaurus"
baseUrl = "https://www.thesaurus.com/"

[duckduckgo]
serviceSearch = "duckduckgo"
baseUrl = "https://duckduckgo.com/"
names = ["duck duck go"]

["duckduckgo images"]
serviceSearch = "ddgi"
baseUrl = "https://duckduckgo.com/"
names = ["duck duck go images"]
["duckduckgo images".baseUrlQueryParameters]
iax = "images"
ia = "images"

["google"]
serviceSearch = "google"
baseUrl = "https://www.google.com"

["google images"]
serviceSearch = "gi"
baseUrl = "https://www.google.com/"
names = ["images"]
["google images".baseUrlQueryParameters]
tbm = "isch"

[imdb]
serviceSearch = "imdb"
baseUrl = "https://www.imdb.com/"

[add-ons]
serviceSearch = "mozaddon"
baseUrl = "https://addons.mozilla.org/"
names = ["firefox add-ons", "mozilla add-ons"]

[github]
serviceSearch = "github"
baseUrl = "https://github.com"

[justwatch] 
serviceSearch = "justwatch"
baseUrl = "https://www.justwatch.com/"

[reelgood]
serviceSearch = "reelgood"
baseUrl = "https://reelgood.com/"

[linguee]
serviceSearch = "linguee"
baseUrl = "https://www.linguee.com/"

["khan academy"]
serviceSearch = "khanacademy"
baseUrl = "https://www.khanacademy.org/"
