[browser.bookmark]
description = "Open bookmarks"
match = """
  (Open | show | View |) (all | my |) (bookmark{s} |) (sidebar |)
"""

[[browser.bookmark.example]]
phrase = "Bookmark{s}"

[[browser.bookmark.example]]
phrase = "Open bookmark{s}"
test = true

[[browser.bookmark.example]]
phrase = "Show bookmark{s}"
test = true

[[browser.bookmark.example]]
phrase = "Show all bookmark{s}"
test = true

[[browser.bookmark.example]]
phrase = "Show my bookmark{s}"
test = true

[[browser.bookmark.example]]
phrase = "View bookmark{s} sidebar"
test = true

[browser.history]
description = "Open history"
match = """
  (Open | Show |) (all | my |) (browsing | browser |) history
"""

[[browser.history.example]]
phrase = "Open history"

[[browser.history.example]]
phrase = "History"
test = true

[[browser.history.example]]
phrase = "My browsing history"
test = true

[[browser.history.example]]
phrase = "Show history"
test = true

[[browser.history.example]]
phrase = "Show all history"
test = true

[[browser.history.example]]
phrase = "Show my history"
test = true

[browser.preferences]
description = "open browser settings or preferences"
match = """
  (open |) (browser | firefox) (settings | preferences )
"""

[[browser.preferences.example]]
phrase = "open firefox settings"
test = true

[[browser.preferences.example]]
phrase = "firefox settings"
test = true

[browser.addons]
description = "open browser addons or extensions"
match = """
  (open | manage |) (addons | addon | add-ons | add-on | extensions| extension ) (manager |)
"""

[[browser.addons.example]]
phrase = "extensions"

[[browser.addons.example]]
phrase = "open addons"
test = true

[[browser.addons.example]]
phrase = "open extensions"
test = true

[[browser.addons.example]]
phrase = "open addons"
test = true

[[browser.addons.example]]
phrase = "open addon"
test = true

[[browser.addons.example]]
phrase = "open add-ons"
test = true

[[browser.addons.example]]
phrase = "open add-on"
test = true

[[browser.addons.example]]
phrase = "open add-on manager"
test = true

[[browser.addons.example]]
phrase = "manage add-ons"
test = true

[[browser.addons.example]]
phrase = "manage extensions"
test = true
